In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [32]:
#Import Dataset
ds= pd.read_csv("/content/dataset_website.csv.csv")
ds

url  length_url  \
0                  http://www.crestonwood.com/router.php          37   
1      http://shadetreetechnology.com/V4/validation/a...          77   
2      https://support-appleld.com.secureupdate.duila...         126   
3                                     http://rgipt.ac.in          18   
4      http://www.iracing.com/tracks/gateway-motorspo...          55   
...                                                  ...         ...   
11425      http://www.fontspace.com/category/blackletter          45   
11426  http://www.budgetbots.com/server.php/Server%20...          84   
11427  https://www.facebook.com/Interactive-Televisio...         105   
11428             http://www.mypublicdomainpictures.com/          38   
11429  http://174.139.46.123/ap/signin?openid.pape.ma...         477   

       length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  \
0                   19   0        3           0      0      0       0      0   
1                   23   1        1           0      0      0       0      0   
2                   50   1        4           1      0      1       2      0   
3                   11   0        2           0      0      0       0      0   
4                   15   0        2           2      0      0       0      0   
...                ...  ..      ...         ...    ...    ...     ...    ...   
11425               17   0        2           0      0      0       0      0   
11426               18   0        5           0      1      1       0      0   
11427               16   1        2           6      0      1       0      0   
11428               30   0        2           0      0      0       0      0   
11429               14   1       24           0      1      1       9      0   

       ...  domain_in_title  domain_with_copyright  whois_registered_domain  \
0      ...                0                      1                        0   
1      ...                1                      0                        0   
2      ...                1                      0                        0   
3      ...                1                      0                        0   
4      ...                0                      1                        0   
...    ...              ...                    ...                      ...   
11425  ...                0                      0                        0   
11426  ...                1                      0                        0   
11427  ...                0                      0                        0   
11428  ...                1                      0                        0   
11429  ...                1                      1                        1   

       domain_registration_length  domain_age  web_traffic  dns_record  \
0                              45          -1            0           1   
1                              77        5767            0           0   
2                              14        4004      5828815           0   
3                              62          -1       107721           0   
4                             224        8175         8725           0   
...                           ...         ...          ...         ...   
11425                         448        5396         3980           0   
11426                         211        6728            0           0   
11427                        2809        8515            8           0   
11428                          85        2836      2455493           0   
11429                           0          -1            0           1   

       google_index  page_rank      status  
0                 1          4  legitimate  
1                 1          2    phishing  
2                 1          0    phishing  
3                 0          3  legitimate  
4                 0          6  legitimate  
...             ...        ...         ...  
11425             0          6  legitimate  
11426             1          

In [33]:
ds.isnull()

url  length_url  length_hostname     ip  nb_dots  nb_hyphens  nb_at  \
0      False       False            False  False    False       False  False   
1      False       False            False  False    False       False  False   
2      False       False            False  False    False       False  False   
3      False       False            False  False    False       False  False   
4      False       False            False  False    False       False  False   
...      ...         ...              ...    ...      ...         ...    ...   
11425  False       False            False  False    False       False  False   
11426  False       False            False  False    False       False  False   
11427  False       False            False  False    False       False  False   
11428  False       False            False  False    False       False  False   
11429  False       False            False  False    False       False  False   

       nb_qm  nb_and  nb_or  ...  domain_in_title  domain_with_copyright  \
0      False   False  False  ...            False                  False   
1      False   False  False  ...            False                  False   
2      False   False  False  ...            False                  False   
3      False   False  False  ...            False                  False   
4      False   False  False  ...            False                  False   
...      ...     ...    ...  ...              ...                    ...   
11425  False   False  False  ...            False                  False   
11426  False   False  False  ...            False                  False   
11427  False   False  False  ...            False                  False   
11428  False   False  False  ...            False                  False   
11429  False   False  False  ...            False                  False   

       whois_registered_domain  domain_registration_length  domain_age  \
0                        False                       False       False   
1                        False                       False       False   
2                        False                       False       False   
3                        False                       False       False   
4                        False                       False       False   
...                        ...                         ...         ...   
11425                    False                       False       False   
11426                    False                       False       False   
11427                    False                       False       False   
11428                    False                       False       False   
11429                    False                       False       False   

       web_traffic  dns_record  google_index  page_rank  status  
0            False       False         False      False   False  
1            False       False         False      False   False  
2            False       False         False      False   False  
3            False       False         False      False   False  
4            False       False         False      False   False  
...            ...         ...           ...        ...     ...  
11425        False       False         False      False   False  
11426        False       False         False      False   False  
11427        False       False         False      False   False  
11428        False       False         False      False   False  
11429        False       False         False      False   False  

[11430 rows x 89 columns]

In [34]:
#Analysing the data using pandas and Checking if the dataset contains any Null values. ds.info()
ds.isnull().any() #no null values

url                False
length_url         False
length_hostname    False
ip                 False
nb_dots            False
                   ...  
web_traffic        False
dns_record         False
google_index       False
page_rank          False
status             False
Length: 89, dtype: bool

In [35]:
#Splitting data as independent and dependent #removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

[[ 37.  19.   0. ...   0.   0.   0.]
 [ 77.  23.   1. ...   0.   0.   0.]
 [126.  50.   1. ...   0.   0.   0.]
 ...
 [105.  16.   1. ...   0.   0.   0.]
 [ 38.  30.   0. ...   0.   0.   0.]
 [477.  14.   1. ...   0.   0.   1.]] ['legitimate' 'phishing' 'phishing' ... 'legitimate' 'legitimate'
 'phishing']


In [36]:
#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [37]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

# Example data
X = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0], [5.0, 6.0]])
y = np.array([0, 1, 0, 1, 0])

scaler = StandardScaler()
model = LogisticRegression(max_iter=500)  # Increase max_iter
pipeline = make_pipeline(scaler, model)
pipeline.fit(X, y)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=500))])

In [38]:
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score (y_test,y_pred1)
log_reg

0.7939632545931758

In [40]:
import pickle
pickle.dump(lr, open('Phishing_Website.pkl', 'wb'))